%This is the change file for the original Docker's Documentation file.
%This is part of Japanese translation version for Docker's Documantation.

% __SUBDIR__ 対応。/ .md リンクへの (no slash) 対応
% snip 対応

@x
description:
  Learn how to create, manage, and use volumes instead of bind mounts for
  persisting data generated and used by Docker.
title: Volumes
@y
description:
  Learn how to create, manage, and use volumes instead of bind mounts for
  persisting data generated and used by Docker.
title: Volumes
@z

@x
keywords:
  docker compose volumes, docker volumes, docker compose volume, docker volume
  mount, docker mount volume, docker volume create, docker volume location
@y
keywords:
  docker compose volumes, docker volumes, docker compose volume, docker volume
  mount, docker mount volume, docker volume create, docker volume location
@z

@x
Volumes are persistent data stores for containers, created and managed by
Docker. You can create a volume explicitly using the `docker volume create`
command, or Docker can create a volume during container or service creation.
@y
Volumes are persistent data stores for containers, created and managed by
Docker. You can create a volume explicitly using the `docker volume create`
command, or Docker can create a volume during container or service creation.
@z

@x
When you create a volume, it's stored within a directory on the Docker
host. When you mount the volume into a container, this directory is what's
mounted into the container. This is similar to the way that bind mounts work,
except that volumes are managed by Docker and are isolated from the core
functionality of the host machine.
@y
When you create a volume, it's stored within a directory on the Docker
host. When you mount the volume into a container, this directory is what's
mounted into the container. This is similar to the way that bind mounts work,
except that volumes are managed by Docker and are isolated from the core
functionality of the host machine.
@z

@x
## When to use volumes
@y
## When to use volumes
@z

@x
Volumes are the preferred mechanism for persisting data generated by and used
by Docker containers. While [bind mounts](bind-mounts.md) are dependent on the
directory structure and OS of the host machine, volumes are completely managed by
Docker. Volumes are a good choice for the following use cases:
@y
Volumes are the preferred mechanism for persisting data generated by and used
by Docker containers. While [bind mounts](bind-mounts.md) are dependent on the
directory structure and OS of the host machine, volumes are completely managed by
Docker. Volumes are a good choice for the following use cases:
@z

@x
- Volumes are easier to back up or migrate than bind mounts.
- You can manage volumes using Docker CLI commands or the Docker API.
- Volumes work on both Linux and Windows containers.
- Volumes can be more safely shared among multiple containers.
- New volumes can have their content pre-populated by a container or build.
- When your application requires high-performance I/O.
@y
- Volumes are easier to back up or migrate than bind mounts.
- You can manage volumes using Docker CLI commands or the Docker API.
- Volumes work on both Linux and Windows containers.
- Volumes can be more safely shared among multiple containers.
- New volumes can have their content pre-populated by a container or build.
- When your application requires high-performance I/O.
@z

@x
Volumes are not a good choice if you need to access the files from the host, as
the volume is completely managed by Docker. Use [bind mounts](bind-mounts.md)
if you need to access files or directories from both containers and the host.
@y
Volumes are not a good choice if you need to access the files from the host, as
the volume is completely managed by Docker. Use [bind mounts](bind-mounts.md)
if you need to access files or directories from both containers and the host.
@z

@x
Volumes are often a better choice than writing data directly to a container,
because a volume doesn't increase the size of the containers using it. Using a
volume is also faster; writing into a container's writable layer requires a
[storage driver](/manuals/engine/storage/drivers/_index.md) to manage the
filesystem. The storage driver provides a union filesystem, using the Linux
kernel. This extra abstraction reduces performance as compared to using
volumes, which write directly to the host filesystem.
@y
Volumes are often a better choice than writing data directly to a container,
because a volume doesn't increase the size of the containers using it. Using a
volume is also faster; writing into a container's writable layer requires a
[storage driver](manuals/engine/storage/drivers/_index.md) to manage the
filesystem. The storage driver provides a union filesystem, using the Linux
kernel. This extra abstraction reduces performance as compared to using
volumes, which write directly to the host filesystem.
@z

@x
If your container generates non-persistent state data, consider using a
[tmpfs mount](tmpfs.md) to avoid storing the data anywhere permanently, and to
increase the container's performance by avoiding writing into the container's
writable layer.
@y
If your container generates non-persistent state data, consider using a
[tmpfs mount](tmpfs.md) to avoid storing the data anywhere permanently, and to
increase the container's performance by avoiding writing into the container's
writable layer.
@z

@x
Volumes use `rprivate` (recursive private) bind propagation, and bind propagation isn't
configurable for volumes.
@y
Volumes use `rprivate` (recursive private) bind propagation, and bind propagation isn't
configurable for volumes.
@z

@x
## A volume's lifecycle
@y
## A volume's lifecycle
@z

@x
A volume's contents exist outside the lifecycle of a given container. When a
container is destroyed, the writable layer is destroyed with it. Using a volume
ensures that the data is persisted even if the container using it is removed.
@y
A volume's contents exist outside the lifecycle of a given container. When a
container is destroyed, the writable layer is destroyed with it. Using a volume
ensures that the data is persisted even if the container using it is removed.
@z

@x
A given volume can be mounted into multiple containers simultaneously. When no
running container is using a volume, the volume is still available to Docker
and isn't removed automatically. You can remove unused volumes using `docker
volume prune`.
@y
A given volume can be mounted into multiple containers simultaneously. When no
running container is using a volume, the volume is still available to Docker
and isn't removed automatically. You can remove unused volumes using `docker
volume prune`.
@z

@x
## Mounting a volume over existing data
@y
## Mounting a volume over existing data
@z

@x
If you mount a _non-empty volume_ into a directory in the container in which
files or directories exist, the pre-existing files are obscured by the mount.
This is similar to if you were to save files into `/mnt` on a Linux host, and
then mounted a USB drive into `/mnt`. The contents of `/mnt` would be obscured
by the contents of the USB drive until the USB drive was unmounted.
@y
If you mount a _non-empty volume_ into a directory in the container in which
files or directories exist, the pre-existing files are obscured by the mount.
This is similar to if you were to save files into `/mnt` on a Linux host, and
then mounted a USB drive into `/mnt`. The contents of `/mnt` would be obscured
by the contents of the USB drive until the USB drive was unmounted.
@z

@x
With containers, there's no straightforward way of removing a mount to reveal
the obscured files again. Your best option is to recreate the container without
the mount.
@y
With containers, there's no straightforward way of removing a mount to reveal
the obscured files again. Your best option is to recreate the container without
the mount.
@z

@x
If you mount an _empty volume_ into a directory in the container in which files
or directories exist, these files or directories are propagated (copied) into
the volume by default. Similarly, if you start a container and specify a volume
which does not already exist, an empty volume is created for you. This is a
good way to pre-populate data that another container needs.
@y
If you mount an _empty volume_ into a directory in the container in which files
or directories exist, these files or directories are propagated (copied) into
the volume by default. Similarly, if you start a container and specify a volume
which does not already exist, an empty volume is created for you. This is a
good way to pre-populate data that another container needs.
@z

@x
To prevent Docker from copying a container's pre-existing files into an empty
volume, use the `volume-nocopy` option, see [Options for --mount](#options-for---mount).
@y
To prevent Docker from copying a container's pre-existing files into an empty
volume, use the `volume-nocopy` option, see [Options for --mount](#options-for---mount).
@z

@x
## Named and anonymous volumes
@y
## Named and anonymous volumes
@z

@x
A volume may be named or anonymous. Anonymous volumes are given a random name
that's guaranteed to be unique within a given Docker host. Just like named
volumes, anonymous volumes persist even if you remove the container that uses
them, except if you use the `--rm` flag when creating the container, in which
case the anonymous volume associated with the container is destroyed. See
[Remove anonymous volumes](volumes.md#remove-anonymous-volumes).
@y
A volume may be named or anonymous. Anonymous volumes are given a random name
that's guaranteed to be unique within a given Docker host. Just like named
volumes, anonymous volumes persist even if you remove the container that uses
them, except if you use the `--rm` flag when creating the container, in which
case the anonymous volume associated with the container is destroyed. See
[Remove anonymous volumes](volumes.md#remove-anonymous-volumes).
@z

@x
If you create multiple containers consecutively that each use anonymous
volumes, each container creates its own volume. Anonymous volumes aren't reused
or shared between containers automatically. To share an anonymous volume
between two or more containers, you must mount the anonymous volume using the
random volume ID.
@y
If you create multiple containers consecutively that each use anonymous
volumes, each container creates its own volume. Anonymous volumes aren't reused
or shared between containers automatically. To share an anonymous volume
between two or more containers, you must mount the anonymous volume using the
random volume ID.
@z

@x
## Syntax
@y
## Syntax
@z

@x
To mount a volume with the `docker run` command, you can use either the
`--mount` or `--volume` flag.
@y
To mount a volume with the `docker run` command, you can use either the
`--mount` or `--volume` flag.
@z

% snip command...

@x
In general, `--mount` is preferred. The main difference is that the `--mount`
flag is more explicit and supports all the available options.
@y
In general, `--mount` is preferred. The main difference is that the `--mount`
flag is more explicit and supports all the available options.
@z

@x
You must use `--mount` if you want to:
@y
You must use `--mount` if you want to:
@z

@x
- Specify [volume driver options](#use-a-volume-driver)
- Mount a [volume subdirectory](#mount-a-volume-subdirectory)
- Mount a volume into a Swarm service
@y
- Specify [volume driver options](#use-a-volume-driver)
- Mount a [volume subdirectory](#mount-a-volume-subdirectory)
- Mount a volume into a Swarm service
@z

@x
### Options for --mount
@y
### Options for --mount
@z

@x
The `--mount` flag consists of multiple key-value pairs, separated by commas
and each consisting of a `<key>=<value>` tuple. The order of the keys isn't
significant.
@y
The `--mount` flag consists of multiple key-value pairs, separated by commas
and each consisting of a `<key>=<value>` tuple. The order of the keys isn't
significant.
@z

% snip command...

@x
Valid options for `--mount type=volume` include:
@y
Valid options for `--mount type=volume` include:
@z

@x
| Option                         | Description                                                                                                                                                                                                                     |
| ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `source`, `src`                | The source of the mount. For named volumes, this is the name of the volume. For anonymous volumes, this field is omitted.                                                                                                       |
| `destination`, `dst`, `target` | The path where the file or directory is mounted in the container.                                                                                                                                                               |
| `volume-subpath`               | A path to a subdirectory within the volume to mount into the container. The subdirectory must exist in the volume before the volume is mounted to a container. See [Mount a volume subdirectory](#mount-a-volume-subdirectory). |
| `readonly`, `ro`               | If present, causes the volume to be [mounted into the container as read-only](#use-a-read-only-volume).                                                                                                                         |
| `volume-nocopy`                | If present, data at the destination isn't copied into the volume if the volume is empty. By default, content at the target destination gets copied into a mounted volume if empty.                                              |
| `volume-opt`                   | Can be specified more than once, takes a key-value pair consisting of the option name and its value.                                                                                                                            |
@y
| Option                         | Description                                                                                                                                                                                                                     |
| ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `source`, `src`                | The source of the mount. For named volumes, this is the name of the volume. For anonymous volumes, this field is omitted.                                                                                                       |
| `destination`, `dst`, `target` | The path where the file or directory is mounted in the container.                                                                                                                                                               |
| `volume-subpath`               | A path to a subdirectory within the volume to mount into the container. The subdirectory must exist in the volume before the volume is mounted to a container. See [Mount a volume subdirectory](#mount-a-volume-subdirectory). |
| `readonly`, `ro`               | If present, causes the volume to be [mounted into the container as read-only](#use-a-read-only-volume).                                                                                                                         |
| `volume-nocopy`                | If present, data at the destination isn't copied into the volume if the volume is empty. By default, content at the target destination gets copied into a mounted volume if empty.                                              |
| `volume-opt`                   | Can be specified more than once, takes a key-value pair consisting of the option name and its value.                                                                                                                            |
@z

% snip command...

@x
### Options for --volume
@y
### Options for --volume
@z

@x
The `--volume` or `-v` flag consists of three fields, separated by colon
characters (`:`). The fields must be in the correct order.
@y
The `--volume` or `-v` flag consists of three fields, separated by colon
characters (`:`). The fields must be in the correct order.
@z

% snip command...

@x
In the case of named volumes, the first field is the name of the volume, and is
unique on a given host machine. For anonymous volumes, the first field is
omitted. The second field is the path where the file or directory is mounted in
the container.
@y
In the case of named volumes, the first field is the name of the volume, and is
unique on a given host machine. For anonymous volumes, the first field is
omitted. The second field is the path where the file or directory is mounted in
the container.
@z

@x
The third field is optional, and is a comma-separated list of options. Valid
options for `--volume` with a data volume include:
@y
The third field is optional, and is a comma-separated list of options. Valid
options for `--volume` with a data volume include:
@z

@x
| Option           | Description                                                                                                                                                                        |
| ---------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `readonly`, `ro` | If present, causes the volume to be [mounted into the container as read-only](#use-a-read-only-volume).                                                                            |
| `volume-nocopy`  | If present, data at the destination isn't copied into the volume if the volume is empty. By default, content at the target destination gets copied into a mounted volume if empty. |
@y
| Option           | Description                                                                                                                                                                        |
| ---------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `readonly`, `ro` | If present, causes the volume to be [mounted into the container as read-only](#use-a-read-only-volume).                                                                            |
| `volume-nocopy`  | If present, data at the destination isn't copied into the volume if the volume is empty. By default, content at the target destination gets copied into a mounted volume if empty. |
@z

% snip command...

@x
## Create and manage volumes
@y
## Create and manage volumes
@z

@x
Unlike a bind mount, you can create and manage volumes outside the scope of any
container.
@y
Unlike a bind mount, you can create and manage volumes outside the scope of any
container.
@z

@x
Create a volume:
@y
Create a volume:
@z

% snip command...

@x
List volumes:
@y
List volumes:
@z

% snip command...

@x
Inspect a volume:
@y
Inspect a volume:
@z

% snip command...

@x
Remove a volume:
@y
Remove a volume:
@z

% snip command...

@x
## Start a container with a volume
@y
## Start a container with a volume
@z

@x
If you start a container with a volume that doesn't yet exist, Docker creates
the volume for you. The following example mounts the volume `myvol2` into
`/app/` in the container.
@y
If you start a container with a volume that doesn't yet exist, Docker creates
the volume for you. The following example mounts the volume `myvol2` into
`/app/` in the container.
@z

@x
The following `-v` and `--mount` examples produce the same result. You can't
run them both unless you remove the `devtest` container and the `myvol2` volume
after running the first one.
@y
The following `-v` and `--mount` examples produce the same result. You can't
run them both unless you remove the `devtest` container and the `myvol2` volume
after running the first one.
@z

@x
{{< tabs >}}
{{< tab name="`--mount`" >}}
@y
{{< tabs >}}
{{< tab name="`--mount`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< tab name="`-v`" >}}
@y
{{< /tab >}}
{{< tab name="`-v`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< /tabs >}}
@y
{{< /tab >}}
{{< /tabs >}}
@z

@x
Use `docker inspect devtest` to verify that Docker created the volume and it mounted
correctly. Look for the `Mounts` section:
@y
Use `docker inspect devtest` to verify that Docker created the volume and it mounted
correctly. Look for the `Mounts` section:
@z

% snip code...

@x
This shows that the mount is a volume, it shows the correct source and
destination, and that the mount is read-write.
@y
This shows that the mount is a volume, it shows the correct source and
destination, and that the mount is read-write.
@z

@x
Stop the container and remove the volume. Note volume removal is a separate
step.
@y
Stop the container and remove the volume. Note volume removal is a separate
step.
@z

% snip command...

@x
## Use a volume with Docker Compose
@y
## Use a volume with Docker Compose
@z

@x
The following example shows a single Docker Compose service with a volume:
@y
The following example shows a single Docker Compose service with a volume:
@z

% snip code...

@x
Running `docker compose up` for the first time creates a volume. Docker reuses the same volume when you run the command subsequently.
@y
Running `docker compose up` for the first time creates a volume. Docker reuses the same volume when you run the command subsequently.
@z

@x
You can create a volume directly outside of Compose using `docker volume create` and
then reference it inside `compose.yaml` as follows:
@y
You can create a volume directly outside of Compose using `docker volume create` and
then reference it inside `compose.yaml` as follows:
@z

% snip code...

@x
For more information about using volumes with Compose, refer to the
[Volumes](/reference/compose-file/volumes.md)
section in the Compose specification.
@y
For more information about using volumes with Compose, refer to the
[Volumes](reference/compose-file/volumes.md)
section in the Compose specification.
@z

@x
### Start a service with volumes
@y
### Start a service with volumes
@z

@x
When you start a service and define a volume, each service container uses its own
local volume. None of the containers can share this data if you use the `local`
volume driver. However, some volume drivers do support shared storage.
@y
When you start a service and define a volume, each service container uses its own
local volume. None of the containers can share this data if you use the `local`
volume driver. However, some volume drivers do support shared storage.
@z

@x
The following example starts an `nginx` service with four replicas, each of which
uses a local volume called `myvol2`.
@y
The following example starts an `nginx` service with four replicas, each of which
uses a local volume called `myvol2`.
@z

% snip command...

@x
Use `docker service ps devtest-service` to verify that the service is running:
@y
Use `docker service ps devtest-service` to verify that the service is running:
@z

% snip command...

@x
You can remove the service to stop the running tasks:
@y
You can remove the service to stop the running tasks:
@z

% snip command...

@x
Removing the service doesn't remove any volumes created by the service.
Volume removal is a separate step.
@y
Removing the service doesn't remove any volumes created by the service.
Volume removal is a separate step.
@z

@x
### Populate a volume using a container
@y
### Populate a volume using a container
@z

@x
If you start a container which creates a new volume, and the container
has files or directories in the directory to be mounted such as `/app/`,
Docker copies the directory's contents into the volume. The container then
mounts and uses the volume, and other containers which use the volume also
have access to the pre-populated content.
@y
If you start a container which creates a new volume, and the container
has files or directories in the directory to be mounted such as `/app/`,
Docker copies the directory's contents into the volume. The container then
mounts and uses the volume, and other containers which use the volume also
have access to the pre-populated content.
@z

@x
To show this, the following example starts an `nginx` container and
populates the new volume `nginx-vol` with the contents of the container's
`/usr/share/nginx/html` directory. This is where Nginx stores its default HTML
content.
@y
To show this, the following example starts an `nginx` container and
populates the new volume `nginx-vol` with the contents of the container's
`/usr/share/nginx/html` directory. This is where Nginx stores its default HTML
content.
@z

@x
The `--mount` and `-v` examples have the same end result.
@y
The `--mount` and `-v` examples have the same end result.
@z

@x
{{< tabs >}}
{{< tab name="`--mount`" >}}
@y
{{< tabs >}}
{{< tab name="`--mount`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< tab name="`-v`" >}}
@y
{{< /tab >}}
{{< tab name="`-v`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< /tabs >}}
@y
{{< /tab >}}
{{< /tabs >}}
@z

@x
After running either of these examples, run the following commands to clean up
the containers and volumes. Note volume removal is a separate step.
@y
After running either of these examples, run the following commands to clean up
the containers and volumes. Note volume removal is a separate step.
@z

% snip command...

@x
## Use a read-only volume
@y
## Use a read-only volume
@z

@x
For some development applications, the container needs to write into the bind
mount so that changes are propagated back to the Docker host. At other times,
the container only needs read access to the data. Multiple
containers can mount the same volume. You can simultaneously mount a
single volume as `read-write` for some containers and as `read-only` for others.
@y
For some development applications, the container needs to write into the bind
mount so that changes are propagated back to the Docker host. At other times,
the container only needs read access to the data. Multiple
containers can mount the same volume. You can simultaneously mount a
single volume as `read-write` for some containers and as `read-only` for others.
@z

@x
The following example changes the previous one. It mounts the directory as a read-only
volume, by adding `ro` to the (empty by default) list of options, after the
mount point within the container. Where multiple options are present, you can separate
them using commas.
@y
The following example changes the previous one. It mounts the directory as a read-only
volume, by adding `ro` to the (empty by default) list of options, after the
mount point within the container. Where multiple options are present, you can separate
them using commas.
@z

@x
The `--mount` and `-v` examples have the same result.
@y
The `--mount` and `-v` examples have the same result.
@z

@x
{{< tabs >}}
{{< tab name="`--mount`" >}}
@y
{{< tabs >}}
{{< tab name="`--mount`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< tab name="`-v`" >}}
@y
{{< /tab >}}
{{< tab name="`-v`" >}}
@z

% snip command...

@x
{{< /tab >}}
{{< /tabs >}}
@y
{{< /tab >}}
{{< /tabs >}}
@z

@x
Use `docker inspect nginxtest` to verify that Docker created the read-only mount
correctly. Look for the `Mounts` section:
@y
Use `docker inspect nginxtest` to verify that Docker created the read-only mount
correctly. Look for the `Mounts` section:
@z

% snip code...

@x
Stop and remove the container, and remove the volume. Volume removal is a
separate step.
@y
Stop and remove the container, and remove the volume. Volume removal is a
separate step.
@z

% snip command...

@x
## Mount a volume subdirectory
@y
## Mount a volume subdirectory
@z

@x
When you mount a volume to a container, you can specify a subdirectory of the
volume to use, with the `volume-subpath` parameter for the `--mount` flag. The
subdirectory that you specify must exist in the volume before you attempt to
mount it into a container; if it doesn't exist, the mount fails.
@y
When you mount a volume to a container, you can specify a subdirectory of the
volume to use, with the `volume-subpath` parameter for the `--mount` flag. The
subdirectory that you specify must exist in the volume before you attempt to
mount it into a container; if it doesn't exist, the mount fails.
@z

@x
Specifying `volume-subpath` is useful if you only want to share a specific
portion of a volume with a container. Say for example that you have multiple
containers running and you want to store logs from each container in a shared
volume. You can create a subdirectory for each container in the shared volume,
and mount the subdirectory to the container.
@y
Specifying `volume-subpath` is useful if you only want to share a specific
portion of a volume with a container. Say for example that you have multiple
containers running and you want to store logs from each container in a shared
volume. You can create a subdirectory for each container in the shared volume,
and mount the subdirectory to the container.
@z

@x
The following example creates a `logs` volume and initiates the subdirectories
`app1` and `app2` in the volume. It then starts two containers and mounts one
of the subdirectories of the `logs` volume to each container. This example
assumes that the processes in the containers write their logs to
`/var/log/app1` and `/var/log/app2`.
@y
The following example creates a `logs` volume and initiates the subdirectories
`app1` and `app2` in the volume. It then starts two containers and mounts one
of the subdirectories of the `logs` volume to each container. This example
assumes that the processes in the containers write their logs to
`/var/log/app1` and `/var/log/app2`.
@z

% snip command...

@x
With this setup, the containers write their logs to separate subdirectories of
the `logs` volume. The containers can't access the other container's logs.
@y
With this setup, the containers write their logs to separate subdirectories of
the `logs` volume. The containers can't access the other container's logs.
@z

@x
## Share data between machines
@y
## Share data between machines
@z

@x
When building fault-tolerant applications, you may need to configure multiple
replicas of the same service to have access to the same files.
@y
When building fault-tolerant applications, you may need to configure multiple
replicas of the same service to have access to the same files.
@z

@x
![shared storage](images/volumes-shared-storage.webp)
@y
![shared storage](images/volumes-shared-storage.webp)
@z

@x
There are several ways to achieve this when developing your applications.
One is to add logic to your application to store files on a cloud object
storage system like Amazon S3. Another is to create volumes with a driver that
supports writing files to an external storage system like NFS or Amazon S3.
@y
There are several ways to achieve this when developing your applications.
One is to add logic to your application to store files on a cloud object
storage system like Amazon S3. Another is to create volumes with a driver that
supports writing files to an external storage system like NFS or Amazon S3.
@z

@x
Volume drivers let you abstract the underlying storage system from the
application logic. For example, if your services use a volume with an NFS
driver, you can update the services to use a different driver. For example, to
store data in the cloud, without changing the application logic.
@y
Volume drivers let you abstract the underlying storage system from the
application logic. For example, if your services use a volume with an NFS
driver, you can update the services to use a different driver. For example, to
store data in the cloud, without changing the application logic.
@z

@x
## Use a volume driver
@y
## Use a volume driver
@z

@x
When you create a volume using `docker volume create`, or when you start a
container which uses a not-yet-created volume, you can specify a volume driver.
The following examples use the `vieux/sshfs` volume driver, first when creating
a standalone volume, and then when starting a container which creates a new
volume.
@y
When you create a volume using `docker volume create`, or when you start a
container which uses a not-yet-created volume, you can specify a volume driver.
The following examples use the `vieux/sshfs` volume driver, first when creating
a standalone volume, and then when starting a container which creates a new
volume.
@z

@x
> [!NOTE]
>
> If your volume driver accepts a comma-separated list as an option,
> you must escape the value from the outer CSV parser. To escape a `volume-opt`,
> surround it with double quotes (`"`) and surround the entire mount parameter
> with single quotes (`'`).
>
> For example, the `local` driver accepts mount options as a comma-separated
> list in the `o` parameter. This example shows the correct way to escape the list.
>
> ```console
> $ docker service create \
>  --mount 'type=volume,src=<VOLUME-NAME>,dst=<CONTAINER-PATH>,volume-driver=local,volume-opt=type=nfs,volume-opt=device=<nfs-server>:<nfs-path>,"volume-opt=o=addr=<nfs-address>,vers=4,soft,timeo=180,bg,tcp,rw"'
>  --name myservice \
>  <IMAGE>
> ```
@y
> [!NOTE]
>
> If your volume driver accepts a comma-separated list as an option,
> you must escape the value from the outer CSV parser. To escape a `volume-opt`,
> surround it with double quotes (`"`) and surround the entire mount parameter
> with single quotes (`'`).
>
> For example, the `local` driver accepts mount options as a comma-separated
> list in the `o` parameter. This example shows the correct way to escape the list.
>
> ```console
> $ docker service create \
>  --mount 'type=volume,src=<VOLUME-NAME>,dst=<CONTAINER-PATH>,volume-driver=local,volume-opt=type=nfs,volume-opt=device=<nfs-server>:<nfs-path>,"volume-opt=o=addr=<nfs-address>,vers=4,soft,timeo=180,bg,tcp,rw"'
>  --name myservice \
>  <IMAGE>
> ```
@z

@x
### Initial setup
@y
### Initial setup
@z

@x
The following example assumes that you have two nodes, the first of which is a Docker
host and can connect to the second node using SSH.
@y
The following example assumes that you have two nodes, the first of which is a Docker
host and can connect to the second node using SSH.
@z

@x
On the Docker host, install the `vieux/sshfs` plugin:
@y
On the Docker host, install the `vieux/sshfs` plugin:
@z

% snip command...

@x
### Create a volume using a volume driver
@y
### Create a volume using a volume driver
@z

@x
This example specifies an SSH password, but if the two hosts have shared keys
configured, you can exclude the password. Each volume driver may have zero or more
configurable options, you specify each of them using an `-o` flag.
@y
This example specifies an SSH password, but if the two hosts have shared keys
configured, you can exclude the password. Each volume driver may have zero or more
configurable options, you specify each of them using an `-o` flag.
@z

% snip command...

@x
### Start a container which creates a volume using a volume driver
@y
### Start a container which creates a volume using a volume driver
@z

@x
The following example specifies an SSH password. However, if the two hosts have
shared keys configured, you can exclude the password.
Each volume driver may have zero or more configurable options.
@y
The following example specifies an SSH password. However, if the two hosts have
shared keys configured, you can exclude the password.
Each volume driver may have zero or more configurable options.
@z

@x
> [!NOTE]
>
> If the volume driver requires you to pass any options,
> you must use the `--mount` flag to mount the volume, and not `-v`.
@y
> [!NOTE]
>
> If the volume driver requires you to pass any options,
> you must use the `--mount` flag to mount the volume, and not `-v`.
@z

% snip command...

@x
### Create a service which creates an NFS volume
@y
### Create a service which creates an NFS volume
@z

@x
The following example shows how you can create an NFS volume when creating a service.
It uses `10.0.0.10` as the NFS server and `/var/docker-nfs` as the exported directory on the NFS server.
Note that the volume driver specified is `local`.
@y
The following example shows how you can create an NFS volume when creating a service.
It uses `10.0.0.10` as the NFS server and `/var/docker-nfs` as the exported directory on the NFS server.
Note that the volume driver specified is `local`.
@z

@x
#### NFSv3
@y
#### NFSv3
@z

% snip command...

@x
#### NFSv4
@y
#### NFSv4
@z

% snip command...

@x
### Create CIFS/Samba volumes
@y
### Create CIFS/Samba volumes
@z

@x
You can mount a Samba share directly in Docker without configuring a mount point on your host.
@y
You can mount a Samba share directly in Docker without configuring a mount point on your host.
@z

% snip command...

@x
The `addr` option is required if you specify a hostname instead of an IP.
This lets Docker perform the hostname lookup.
@y
The `addr` option is required if you specify a hostname instead of an IP.
This lets Docker perform the hostname lookup.
@z

@x
### Block storage devices
@y
### Block storage devices
@z

@x
You can mount a block storage device, such as an external drive or a drive partition, to a container.
The following example shows how to create and use a file as a block storage device,
and how to mount the block device as a container volume.
@y
You can mount a block storage device, such as an external drive or a drive partition, to a container.
The following example shows how to create and use a file as a block storage device,
and how to mount the block device as a container volume.
@z

@x
> [!IMPORTANT]
>
> The following procedure is only an example.
> The solution illustrated here isn't recommended as a general practice.
> Don't attempt this approach unless you're confident about what you're doing.
@y
> [!IMPORTANT]
>
> The following procedure is only an example.
> The solution illustrated here isn't recommended as a general practice.
> Don't attempt this approach unless you're confident about what you're doing.
@z

@x
#### How mounting block devices works
@y
#### How mounting block devices works
@z

@x
Under the hood, the `--mount` flag using the `local` storage driver invokes the
Linux `mount` syscall and forwards the options you pass to it unaltered.
Docker doesn't implement any additional functionality on top of the native mount features supported by the Linux kernel.
@y
Under the hood, the `--mount` flag using the `local` storage driver invokes the
Linux `mount` syscall and forwards the options you pass to it unaltered.
Docker doesn't implement any additional functionality on top of the native mount features supported by the Linux kernel.
@z

@x
If you're familiar with the
[Linux `mount` command](https://man7.org/linux/man-pages/man8/mount.8.html),
you can think of the `--mount` options as forwarded to the `mount` command in the following manner:
@y
If you're familiar with the
[Linux `mount` command](https://man7.org/linux/man-pages/man8/mount.8.html),
you can think of the `--mount` options as forwarded to the `mount` command in the following manner:
@z

% snip command...

@x
To explain this further, consider the following `mount` command example.
This command mounts the `/dev/loop5` device to the path `/external-drive` on the system.
@y
To explain this further, consider the following `mount` command example.
This command mounts the `/dev/loop5` device to the path `/external-drive` on the system.
@z

% snip command...

@x
The following `docker run` command achieves a similar result, from the point of view of the container being run.
Running a container with this `--mount` option sets up the mount in the same way as if you had executed the
`mount` command from the previous example.
@y
The following `docker run` command achieves a similar result, from the point of view of the container being run.
Running a container with this `--mount` option sets up the mount in the same way as if you had executed the
`mount` command from the previous example.
@z

% snip command...

@x
You can't run the `mount` command inside the container directly,
because the container is unable to access the `/dev/loop5` device.
That's why the `docker run` command uses the `--mount` option.
@y
You can't run the `mount` command inside the container directly,
because the container is unable to access the `/dev/loop5` device.
That's why the `docker run` command uses the `--mount` option.
@z

@x
#### Example: Mounting a block device in a container
@y
#### Example: Mounting a block device in a container
@z

@x
The following steps create an `ext4` filesystem and mounts it into a container.
The filesystem support of your system depends on the version of the Linux kernel you are using.
@y
The following steps create an `ext4` filesystem and mounts it into a container.
The filesystem support of your system depends on the version of the Linux kernel you are using.
@z

@x
1. Create a file and allocate some space to it:
@y
1. Create a file and allocate some space to it:
@z

% snip command...

@x
2. Build a filesystem onto the `disk.raw` file:
@y
2. Build a filesystem onto the `disk.raw` file:
@z

% snip command...

@x
3. Create a loop device:
@y
3. Create a loop device:
@z

% snip command...

@x
   > [!NOTE]
   >
   > `losetup` creates an ephemeral loop device that's removed after
   > system reboot, or manually removed with `losetup -d`.
@y
   > [!NOTE]
   >
   > `losetup` creates an ephemeral loop device that's removed after
   > system reboot, or manually removed with `losetup -d`.
@z

@x
4. Run a container that mounts the loop device as a volume:
@y
4. Run a container that mounts the loop device as a volume:
@z

% snip command...

@x
   When the container starts, the path `/external-drive` mounts the
   `disk.raw` file from the host filesystem as a block device.
@y
   When the container starts, the path `/external-drive` mounts the
   `disk.raw` file from the host filesystem as a block device.
@z

@x
5. When you're done, and the device is unmounted from the container,
   detach the loop device to remove the device from the host system:
@y
5. When you're done, and the device is unmounted from the container,
   detach the loop device to remove the device from the host system:
@z

% snip command...

@x
## Back up, restore, or migrate data volumes
@y
## Back up, restore, or migrate data volumes
@z

@x
Volumes are useful for backups, restores, and migrations.
Use the `--volumes-from` flag to create a new container that mounts that volume.
@y
Volumes are useful for backups, restores, and migrations.
Use the `--volumes-from` flag to create a new container that mounts that volume.
@z

@x
### Back up a volume
@y
### Back up a volume
@z

@x
For example, create a new container named `dbstore`:
@y
For example, create a new container named `dbstore`:
@z

% snip command...

@x
In the next command:
@y
In the next command:
@z

@x
- Launch a new container and mount the volume from the `dbstore` container
- Mount a local host directory as `/backup`
- Pass a command that tars the contents of the `dbdata` volume to a `backup.tar` file inside the `/backup` directory.
@y
- Launch a new container and mount the volume from the `dbstore` container
- Mount a local host directory as `/backup`
- Pass a command that tars the contents of the `dbdata` volume to a `backup.tar` file inside the `/backup` directory.
@z

% snip command...

@x
When the command completes and the container stops, it creates a backup of
the `dbdata` volume.
@y
When the command completes and the container stops, it creates a backup of
the `dbdata` volume.
@z

@x
### Restore volume from a backup
@y
### Restore volume from a backup
@z

@x
With the backup just created, you can restore it to the same container,
or to another container that you created elsewhere.
@y
With the backup just created, you can restore it to the same container,
or to another container that you created elsewhere.
@z

@x
For example, create a new container named `dbstore2`:
@y
For example, create a new container named `dbstore2`:
@z

% snip command...

@x
Then, un-tar the backup file in the new container’s data volume:
@y
Then, un-tar the backup file in the new container’s data volume:
@z

% snip command...

@x
You can use these techniques to automate backup, migration, and restore
testing using your preferred tools.
@y
You can use these techniques to automate backup, migration, and restore
testing using your preferred tools.
@z

@x
## Remove volumes
@y
## Remove volumes
@z

@x
A Docker data volume persists after you delete a container. There are two types
of volumes to consider:
@y
A Docker data volume persists after you delete a container. There are two types
of volumes to consider:
@z

@x
- Named volumes have a specific source from outside the container, for example, `awesome:/bar`.
- Anonymous volumes have no specific source. Therefore, when the container is deleted, you can instruct the Docker Engine daemon to remove them.
@y
- Named volumes have a specific source from outside the container, for example, `awesome:/bar`.
- Anonymous volumes have no specific source. Therefore, when the container is deleted, you can instruct the Docker Engine daemon to remove them.
@z

@x
### Remove anonymous volumes
@y
### Remove anonymous volumes
@z

@x
To automatically remove anonymous volumes, use the `--rm` option. For example,
this command creates an anonymous `/foo` volume. When you remove the container,
the Docker Engine removes the `/foo` volume but not the `awesome` volume.
@y
To automatically remove anonymous volumes, use the `--rm` option. For example,
this command creates an anonymous `/foo` volume. When you remove the container,
the Docker Engine removes the `/foo` volume but not the `awesome` volume.
@z

% snip command...

@x
> [!NOTE]
>
> If another container binds the volumes with
> `--volumes-from`, the volume definitions are _copied_ and the
> anonymous volume also stays after the first container is removed.
@y
> [!NOTE]
>
> If another container binds the volumes with
> `--volumes-from`, the volume definitions are _copied_ and the
> anonymous volume also stays after the first container is removed.
@z

@x
### Remove all volumes
@y
### Remove all volumes
@z

@x
To remove all unused volumes and free up space:
@y
To remove all unused volumes and free up space:
@z

% snip command...

@x
## Next steps
@y
## Next steps
@z

@x
- Learn about [bind mounts](bind-mounts.md).
- Learn about [tmpfs mounts](tmpfs.md).
- Learn about [storage drivers](/engine/storage/drivers/).
- Learn about [third-party volume driver plugins](/engine/extend/legacy_plugins/).
@y
- Learn about [bind mounts](bind-mounts.md).
- Learn about [tmpfs mounts](tmpfs.md).
- Learn about [storage drivers](__SUBDIR__/engine/storage/drivers/).
- Learn about [third-party volume driver plugins](__SUBDIR__/engine/extend/legacy_plugins/).
@z
