##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = compose

bases = \
	_index.md                  \
	daemon-cfg-desktop.md      \
	desktop-license-update.md  \
	desktop-linux-launch.md    \
	engine-license.md          \
	extensions-form.md         \
	hub-categories.md          \
	install-script.md          \
	root-errors.md             \
	sandboxes-local-scope.md   \
	swarm-compose-compat.md    \
	swarm-mode.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
