##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = agents agentsignore budget commands flavors hcl hooks models \
	overview permissions routing sandbox structured-output tools   \
	user-settings

bases = \
	_index.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
