##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md         \
	base-images.md    \
	build-an-agent.md \
	distribute.md     \
	kit-sets.md       \
	patterns.md       \
	tool-mixins.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
