##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md                    \
	ai-governance.md             \
	dhi.md                       \
	docker-agentic-platform.md   \
	docker-verified-publisher.md \
	docker.md                    \
	gordon.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
