##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = agents cloud configuration customize diagrams governance \
	images integrations security workflows

bases = \
	_index.md               \
	architecture.md         \
	faq.md                  \
	get-started.md          \
	install.md              \
	mcp-gateway.md          \
	release-notes.md        \
	troubleshooting.md      \
	usage.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
