%This is the change file for the original Docker's Documentation file.
%This is part of Japanese translation version for Docker's Documantation.

@x
---
description: Automatically lock Swarm managers to protect encryption keys
keywords: swarm, manager, lock, unlock, autolock, encryption
title: Lock your swarm to protect its encryption key
---
@y
---
description: Automatically lock Swarm managers to protect encryption keys
keywords: swarm, manager, lock, unlock, autolock, encryption
title: Lock your swarm to protect its encryption key
---
@z

@x
The Raft logs used by swarm managers are encrypted on disk by default. This at-rest
encryption protects your service's configuration and data from attackers who gain
access to the encrypted Raft logs. One of the reasons this feature was introduced
was in support of the [Docker secrets](secrets.md) feature.
@y
The Raft logs used by swarm managers are encrypted on disk by default. This at-rest
encryption protects your service's configuration and data from attackers who gain
access to the encrypted Raft logs. One of the reasons this feature was introduced
was in support of the [Docker secrets](secrets.md) feature.
@z

@x
When Docker restarts, both the TLS key used to encrypt communication among swarm
nodes and the key used to encrypt and decrypt Raft logs on disk are loaded
into each manager node's memory. Docker has the ability to protect the mutual TLS
encryption key and the key used to encrypt and decrypt Raft logs at rest, by
allowing you to take ownership of these keys and to require manual unlocking of
your managers. This feature is called _autolock_.
@y
When Docker restarts, both the TLS key used to encrypt communication among swarm
nodes and the key used to encrypt and decrypt Raft logs on disk are loaded
into each manager node's memory. Docker has the ability to protect the mutual TLS
encryption key and the key used to encrypt and decrypt Raft logs at rest, by
allowing you to take ownership of these keys and to require manual unlocking of
your managers. This feature is called _autolock_.
@z

@x
When Docker restarts, you must
[unlock the swarm](#unlock-a-swarm) first, using a
_key encryption key_ generated by Docker when the swarm was locked. You can
rotate this key encryption key at any time.
@y
When Docker restarts, you must
[unlock the swarm](#unlock-a-swarm) first, using a
_key encryption key_ generated by Docker when the swarm was locked. You can
rotate this key encryption key at any time.
@z

@x
> **Note**: You don't need to unlock the swarm when a new node joins the swarm,
> because the key is propagated to it over mutual TLS.
@y
> **Note**: You don't need to unlock the swarm when a new node joins the swarm,
> because the key is propagated to it over mutual TLS.
@z

@x
## Initialize a swarm with autolocking enabled
@y
## Initialize a swarm with autolocking enabled
@z

@x
When you initialize a new swarm, you can use the `--autolock` flag to
enable autolocking of swarm manager nodes when Docker restarts.
@y
When you initialize a new swarm, you can use the `--autolock` flag to
enable autolocking of swarm manager nodes when Docker restarts.
@z

@x
```console
$ docker swarm init --autolock
@y
```console
$ docker swarm init --autolock
@z

@x
Swarm initialized: current node (k1q27tfyx9rncpixhk69sa61v) is now a manager.
@y
Swarm initialized: current node (k1q27tfyx9rncpixhk69sa61v) is now a manager.
@z

@x
To add a worker to this swarm, run the following command:
@y
To add a worker to this swarm, run the following command:
@z

@x
    docker swarm join \
    --token SWMTKN-1-0j52ln6hxjpxk2wgk917abcnxywj3xed0y8vi1e5m9t3uttrtu-7bnxvvlz2mrcpfonjuztmtts9 \
    172.31.46.109:2377
@y
    docker swarm join \
    --token SWMTKN-1-0j52ln6hxjpxk2wgk917abcnxywj3xed0y8vi1e5m9t3uttrtu-7bnxvvlz2mrcpfonjuztmtts9 \
    172.31.46.109:2377
@z

@x
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
@y
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
@z

@x
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@y
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@z

@x
    SWMKEY-1-WuYH/IX284+lRcXuoVf38viIDK3HJEKY13MIHX+tTt8
```
@y
    SWMKEY-1-WuYH/IX284+lRcXuoVf38viIDK3HJEKY13MIHX+tTt8
```
@z

@x
Store the key in a safe place, such as in a password manager.
@y
Store the key in a safe place, such as in a password manager.
@z

@x
When Docker restarts, you need to [unlock the swarm](#unlock-a-swarm). A locked
swarm causes an error like the following when you try to start or restart a
service:
@y
When Docker restarts, you need to [unlock the swarm](#unlock-a-swarm). A locked
swarm causes an error like the following when you try to start or restart a
service:
@z

@x
```console
$ sudo service docker restart
@y
```console
$ sudo service docker restart
@z

@x
$ docker service ls
@y
$ docker service ls
@z

@x
Error response from daemon: Swarm is encrypted and needs to be unlocked before it can be used. Use "docker swarm unlock" to unlock it.
```
@y
Error response from daemon: Swarm is encrypted and needs to be unlocked before it can be used. Use "docker swarm unlock" to unlock it.
```
@z

@x
## Enable or disable autolock on an existing swarm
@y
## Enable or disable autolock on an existing swarm
@z

@x
To enable autolock on an existing swarm, set the `autolock` flag to `true`.
@y
To enable autolock on an existing swarm, set the `autolock` flag to `true`.
@z

@x
```console
$ docker swarm update --autolock=true
@y
```console
$ docker swarm update --autolock=true
@z

@x
Swarm updated.
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@y
Swarm updated.
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@z

@x
    SWMKEY-1-+MrE8NgAyKj5r3NcR4FiQMdgu+7W72urH0EZeSmP/0Y
@y
    SWMKEY-1-+MrE8NgAyKj5r3NcR4FiQMdgu+7W72urH0EZeSmP/0Y
@z

@x
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@y
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@z

@x
To disable autolock, set `--autolock` to `false`. The mutual TLS key and the
encryption key used to read and write Raft logs are stored unencrypted on
disk. There is a trade-off between the risk of storing the encryption key
unencrypted at rest and the convenience of restarting a swarm without
needing to unlock each manager.
@y
To disable autolock, set `--autolock` to `false`. The mutual TLS key and the
encryption key used to read and write Raft logs are stored unencrypted on
disk. There is a trade-off between the risk of storing the encryption key
unencrypted at rest and the convenience of restarting a swarm without
needing to unlock each manager.
@z

@x
```console
$ docker swarm update --autolock=false
```
@y
```console
$ docker swarm update --autolock=false
```
@z

@x
Keep the unlock key around for a short time after disabling autolocking, in case
a manager goes down while it is still configured to lock using the old key.
@y
Keep the unlock key around for a short time after disabling autolocking, in case
a manager goes down while it is still configured to lock using the old key.
@z

@x
## Unlock a swarm
@y
## Unlock a swarm
@z

@x
To unlock a locked swarm, use `docker swarm unlock`.
@y
To unlock a locked swarm, use `docker swarm unlock`.
@z

@x
```console
$ docker swarm unlock
@y
```console
$ docker swarm unlock
@z

@x
Please enter unlock key:
```
@y
Please enter unlock key:
```
@z

@x
Enter the encryption key that was generated and shown in the command output when
you locked the swarm or rotated the key, and the swarm unlocks.
@y
Enter the encryption key that was generated and shown in the command output when
you locked the swarm or rotated the key, and the swarm unlocks.
@z

@x
## View the current unlock key for a running swarm
@y
## View the current unlock key for a running swarm
@z

@x
Consider a situation where your swarm is running as expected, then a manager
node becomes unavailable. You troubleshoot the problem and bring the physical
node back online, but you need to unlock the manager by providing the unlock
key to read the encrypted credentials and Raft logs.
@y
Consider a situation where your swarm is running as expected, then a manager
node becomes unavailable. You troubleshoot the problem and bring the physical
node back online, but you need to unlock the manager by providing the unlock
key to read the encrypted credentials and Raft logs.
@z

@x
If the key has not been rotated since the node left the swarm, and you have a
quorum of functional manager nodes in the swarm, you can view the current unlock
key using `docker swarm unlock-key` without any arguments.
@y
If the key has not been rotated since the node left the swarm, and you have a
quorum of functional manager nodes in the swarm, you can view the current unlock
key using `docker swarm unlock-key` without any arguments.
@z

@x
```console
$ docker swarm unlock-key
@y
```console
$ docker swarm unlock-key
@z

@x
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@y
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@z

@x
    SWMKEY-1-8jDgbUNlJtUe5P/lcr9IXGVxqZpZUXPzd+qzcGp4ZYA
@y
    SWMKEY-1-8jDgbUNlJtUe5P/lcr9IXGVxqZpZUXPzd+qzcGp4ZYA
@z

@x
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@y
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@z

@x
If the key was rotated after the swarm node became unavailable and you do not
have a record of the previous key, you may need to force the manager to leave
the swarm and join it back to the swarm as a new manager.
@y
If the key was rotated after the swarm node became unavailable and you do not
have a record of the previous key, you may need to force the manager to leave
the swarm and join it back to the swarm as a new manager.
@z

@x
## Rotate the unlock key
@y
## Rotate the unlock key
@z

@x
You should rotate the locked swarm's unlock key on a regular schedule.
@y
You should rotate the locked swarm's unlock key on a regular schedule.
@z

@x
```console
$ docker swarm unlock-key --rotate
@y
```console
$ docker swarm unlock-key --rotate
@z

@x
Successfully rotated manager unlock key.
@y
Successfully rotated manager unlock key.
@z

@x
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@y
To unlock a swarm manager after it restarts, run the `docker swarm unlock`
command and provide the following key:
@z

@x
    SWMKEY-1-8jDgbUNlJtUe5P/lcr9IXGVxqZpZUXPzd+qzcGp4ZYA
@y
    SWMKEY-1-8jDgbUNlJtUe5P/lcr9IXGVxqZpZUXPzd+qzcGp4ZYA
@z

@x
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@y
Please remember to store this key in a password manager, since without it you
will not be able to restart the manager.
```
@z

@x
> **Warning**:
> When you rotate the unlock key, keep a record of the old key
> around for a few minutes, so that if a manager goes down before it gets the new
> key, it may still be unlocked with the old one.
{ .warning }
@y
> **Warning**:
> When you rotate the unlock key, keep a record of the old key
> around for a few minutes, so that if a manager goes down before it gets the new
> key, it may still be unlocked with the old one.
{ .warning }
@z
