# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: "Docs-ja の問題"
description: "docker.docs-ja (Docker 日本語ドキュメント) の不適切な内容あるいはリンク切れについて、またウェブサイト上の問題についてお知らせください。"
labels:
  - status/triage

body:
  - type: checkboxes
    attributes:
      label: Docker 日本語ドキュメントについての問題ですか？
      description: |
        Docker ドキュメント(日本語訳)に関連した問題点をご報告ください。
        製品の問題やオリジナルドキュメントの問題については、対応するリポジトリを参照してください。
        これは **オリジナル英文のドキュメントに対する issue 報告ではありません**。
        ご注意ください。
      options:
        - label: 問題点の指摘は **Docker 日本語訳について** のドキュメント内容またはウェブサイト上の問題である。
          required: true
  - type: dropdown
    attributes:
      label: 不備の種類
      description: ご報告頂くのはどのような問題ですか？
      multiple: false
      options:
        - 情報が正しくない
        - 求めているものが見つけられない
        - ウェブサイト上の問題がある
        - 日本語訳に問題がある
        - その他
    validations:
      required: true
  - type: textarea
    attributes:
      label: 不備内容
      description: |
        発見した問題点を簡潔にご説明ください。
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: 不備の場所
      description: どこで問題を見つけましたか？
      placeholder: "https://github.com/matsuand/docker.docs-ja/"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ご提案
      description: >
        どのように問題を修正すれば良いか、何かお考えがあれば教えてください。
