##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = a2a acp api-server board chat-server cli code-mode     \
	evaluation harnesses mcp-mode remote-mcp sessions skills \
	snapshots tui

bases = \
	_index.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
