##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md             \
	deactivate-account.md \
	general-settings.md   \
	manage-a-team.md      \
	manage-licenses.md    \
	manage-products.md    \
	manage-seats.md       \
	members.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
