##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	style.css     \
	utilities.css

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk

copyfiles = \
	components.css          \
	global.css              \
	hack.css                \
	interactive-diagram.css \
	pagefind.css            \
	syntax-dark.css         \
	syntax-light.css        \
	theme.css

include $(top_srcdir)/build-aux/copy.mk
