##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md            \
	build.md             \
	customize.md         \
	hardened-packages.md \
	helm.md              \
	mirror.md            \
	policies.md          \
	scan.md              \
	search-evaluate.md   \
	select-enterprise.md \
	troubleshoot.md      \
	use.md               \
	verify.md            \
	vex-api.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
