##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md            \
	credentials.md       \
	environment-files.md \
	gpu-passthrough.md   \
	models.md            \
	registry-mirror.md   \
	settings.md          \
	upstream-proxy.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
