##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	docker_pass.yaml                         \
	docker_pass_get.yaml                     \
	docker_pass_ls.yaml                      \
	docker_pass_plugins.yaml                 \
	docker_pass_plugins_disable.yaml         \
	docker_pass_plugins_enable.yaml          \
	docker_pass_plugins_ls.yaml              \
	docker_pass_run.yaml                     \
	docker_pass_rm.yaml                      \
	docker_pass_plugins_1password.yaml       \
	docker_pass_plugins_1password_purge.yaml \
	docker_pass_plugins_1password_setup.yaml \
	docker_pass_set.yaml


include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
