##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = cookbook

bases = \
	_index.md         \
	authentication.md \
	concepts.md       \
	errors.md         \
	get-started.md    \
	install.md        \
	limits.md         \
	reference.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
