##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	desktop-install.html     \
	desktop-install-v2.html  \
	experimental.html        \
	files.markdown.md        \
	interactive-diagram.html \
	labspace-launch.html     \
	restricted.html          \
	sandbox-auth.html        \
	sandbox-auth.markdown.md \
	summary-bar.html         \
	whats-new.markdown.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk

copyfiles = \
	accordion.html                  \
	accordion.markdown.md           \
	badge.html                      \
	badge.markdown.md               \
	button.html                     \
	button.markdown.md              \
	card.html                       \
	card.markdown.md                \
	desktop-install-v2.markdown.md  \
	experimental.markdown.md        \
	file.html                       \
	files.html                      \
	grid.html                       \
	grid.markdown.md                \
	include.html                    \
	inline-image.html               \
	inline-image.markdown.md        \
	interactive-diagram.markdown.md \
	release-date.html               \
	restricted.markdown.md          \
	sectionlinks.html               \
	summary-bar.markdown.md         \
	tab.html                        \
	tabs.html                       \
	tabs.markdown.md                \
	youtube-embed.html              \
	youtube-embed.markdown.md

include $(top_srcdir)/build-aux/copy.mk
