##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = admonitions api-ref api-reference components sidebar utils

bases = \
	footer.html       \
	github-links.html \
	head.html         \
	header.html       \
	heading.html      \
	md-dropdown.html  \
	search-bar.html   \
	whats-new.html

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk

copyfiles = \
	aside.html           \
	breadcrumbs.html     \
	content-default.html \
	gordon-chat.html     \
	icon.html            \
	mermaid-script.html  \
	meta.html            \
	pagemeta.html        \
	pagefind-meta.html   \
	schema.html          \
	tooltip.html         \
	youtube-script.html

include $(top_srcdir)/build-aux/copy.mk
