##
## This is part of Japanese translation version for Docker's Documantation.
##

copyfiles = \
	gordon_advanced_tool_config.avif \
	gordon_gui.avif                  \
	gordon_permission_settings.avif  \
	gordon_permissions_prompt.avif   \
	gordon_tui.avif

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/copy.mk
