##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	manual-link.html \
	navigation.html  \
	schema.html      \
	websocket.html

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk

copyfiles = \
	description.html   \
	overview-tags.html \
	path.html

include $(top_srcdir)/build-aux/copy.mk
