##
## This is part of Japanese translation version for Docker's Documantation.
##

SUBDIRS = anthropic baseten bedrock cerebras chatgpt                \
	cloudflare-ai-gateway cloudflare-workers-ai custom deepseek \
	dmr fireworks github-copilot google groq huggingface local  \
	minimax mistral moonshot nebius nvidia openai opencode-go   \
	opencode-zen openrouter overview ovhcloud together vercel   \
	xai

bases = \
	_index.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
