##
## This is part of Japanese translation version for Docker's Documantation.
##

bases = \
	_index.md           \
	configure.md        \
	local.md            \
	record-reference.md \
	siem.md             \
	view-export.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/main.mk
