%This is the change file for the original Docker's Documentation file.
%This is part of Japanese translation version for Docker's Documantation.

@x
title: SLSA definitions
@y
title: SLSA definitions
@z

@x
BuildKit supports the [creation of SLSA Provenance](./slsa-provenance.md) for
builds that it runs.
@y
BuildKit supports the [creation of SLSA Provenance](./slsa-provenance.md) for
builds that it runs.
@z

@x
The provenance format generated by BuildKit is defined by the
SLSA Provenance format (supports both [v0.2](https://slsa.dev/spec/v0.2/provenance)
and [v1](https://slsa.dev/spec/v1.1/provenance)).
@y
The provenance format generated by BuildKit is defined by the
SLSA Provenance format (supports both [v0.2](https://slsa.dev/spec/v0.2/provenance)
and [v1](https://slsa.dev/spec/v1.1/provenance)).
@z

@x
This page describes how BuildKit populate each field, and whether the field gets
included when you generate attestations `mode=min` and `mode=max`.
@y
This page describes how BuildKit populate each field, and whether the field gets
included when you generate attestations `mode=min` and `mode=max`.
@z

@x
## SLSA v1
@y
## SLSA v1
@z

@x
### `buildDefinition.buildType`
@y
### `buildDefinition.buildType`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#buildType
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#buildType
* Included with `mode=min` and `mode=max`.
@z

@x
The `buildDefinition.buildType` field is set to `https://github.com/moby/buildkit/blob/master/docs/attestations/slsa-definitions.md`
and can be used to determine the structure of the provenance content.
@y
The `buildDefinition.buildType` field is set to `https://github.com/moby/buildkit/blob/master/docs/attestations/slsa-definitions.md`
and can be used to determine the structure of the provenance content.
@z

@x
```json
    "buildDefinition": {
      "buildType": "https://github.com/moby/buildkit/blob/master/docs/attestations/slsa-definitions.md",
      ...
    }
```
@y
```json
    "buildDefinition": {
      "buildType": "https://github.com/moby/buildkit/blob/master/docs/attestations/slsa-definitions.md",
      ...
    }
```
@z

@x
### `buildDefinition.externalParameters.configSource`
@y
### `buildDefinition.externalParameters.configSource`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#externalParameters
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#externalParameters
* Included with `mode=min` and `mode=max`.
@z

@x
Describes the config that initialized the build.
@y
Describes the config that initialized the build.
@z

@x
```json
    "buildDefinition": {
      "externalParameters": {
        "configSource": {
          "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
          "digest": {
            "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
          },
          "path": "Dockerfile"
        },
        ...
      },
    }
```
@y
```json
    "buildDefinition": {
      "externalParameters": {
        "configSource": {
          "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
          "digest": {
            "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
          },
          "path": "Dockerfile"
        },
        ...
      },
    }
```
@z

@x
For builds initialized from a remote context, like a Git or HTTP URL, this
object defines the context URL and its immutable digest in the `uri` and
`digest` fields. For builds using a local frontend, such as a Dockerfile, the
`path` field defines the path for the frontend file that initialized the build
(`filename` frontend option).
@y
For builds initialized from a remote context, like a Git or HTTP URL, this
object defines the context URL and its immutable digest in the `uri` and
`digest` fields. For builds using a local frontend, such as a Dockerfile, the
`path` field defines the path for the frontend file that initialized the build
(`filename` frontend option).
@z

@x
### `buildDefinition.externalParameters.request`
@y
### `buildDefinition.externalParameters.request`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#externalParameters
* Partially included with `mode=min`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#externalParameters
* Partially included with `mode=min`.
@z

@x
Describes build inputs passed to the build.
@y
Describes build inputs passed to the build.
@z

@x
```json
    "buildDefinition": {
      "externalParameters": {
        "request": {
          "frontend": "gateway.v0",
          "args": {
            "build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR": "1",
            "label:FOO": "bar",
            "source": "docker/dockerfile-upstream:master",
            "target": "release"
          },
          "secrets": [
            {
              "id": "GIT_AUTH_HEADER",
              "optional": true
            },
            ...
          ],
          "ssh": [],
          "locals": []
        },
        ...
      },
    }
```
@y
```json
    "buildDefinition": {
      "externalParameters": {
        "request": {
          "frontend": "gateway.v0",
          "args": {
            "build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR": "1",
            "label:FOO": "bar",
            "source": "docker/dockerfile-upstream:master",
            "target": "release"
          },
          "secrets": [
            {
              "id": "GIT_AUTH_HEADER",
              "optional": true
            },
            ...
          ],
          "ssh": [],
          "locals": []
        },
        ...
      },
    }
```
@z

@x
The following fields are included with both `mode=min` and `mode=max`:
@y
The following fields are included with both `mode=min` and `mode=max`:
@z

@x
- `locals` lists any local sources used in the build, including the build
  context and frontend file.
- `frontend` defines type of BuildKit frontend used for the build. Currently,
  this can be `dockerfile.v0` or `gateway.v0`.
- `args` defines the build arguments passed to the BuildKit frontend.
@y
- `locals` lists any local sources used in the build, including the build
  context and frontend file.
- `frontend` defines type of BuildKit frontend used for the build. Currently,
  this can be `dockerfile.v0` or `gateway.v0`.
- `args` defines the build arguments passed to the BuildKit frontend.
@z

@x
  The keys inside the `args` object reflect the options as BuildKit receives
  them. For example, `build-arg` and `label` prefixes are used for build
  arguments and labels, and `target` key defines the target stage that was
  built. The `source` key defines the source image for the Gateway frontend, if
  used.
@y
  The keys inside the `args` object reflect the options as BuildKit receives
  them. For example, `build-arg` and `label` prefixes are used for build
  arguments and labels, and `target` key defines the target stage that was
  built. The `source` key defines the source image for the Gateway frontend, if
  used.
@z

@x
The following fields are only included with `mode=max`:
@y
The following fields are only included with `mode=max`:
@z

@x
- `secrets` defines secrets used during the build. Note that actual secret
  values are not included.
- `ssh` defines the ssh forwards used during the build.
@y
- `secrets` defines secrets used during the build. Note that actual secret
  values are not included.
- `ssh` defines the ssh forwards used during the build.
@z

@x
### `buildDefinition.internalParameters.buildConfig`
@y
### `buildDefinition.internalParameters.buildConfig`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#internalParameters
* Only included with `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#internalParameters
* Only included with `mode=max`.
@z

@x
Defines the build steps performed during the build.
@y
Defines the build steps performed during the build.
@z

@x
BuildKit internally uses LLB definition to execute the build steps. The LLB
definition of the build steps is defined in the
`buildDefinition.internalParameters.buildConfig.llbDefinition` field.
@y
BuildKit internally uses LLB definition to execute the build steps. The LLB
definition of the build steps is defined in the
`buildDefinition.internalParameters.buildConfig.llbDefinition` field.
@z

@x
Each LLB step is the JSON definition of the
[LLB ProtoBuf API](https://github.com/moby/buildkit/blob/v0.10.0/solver/pb/ops.proto).
The dependencies for a vertex in the LLB graph can be found in the `inputs`
field for every step.
@y
Each LLB step is the JSON definition of the
[LLB ProtoBuf API](https://github.com/moby/buildkit/blob/v0.10.0/solver/pb/ops.proto).
The dependencies for a vertex in the LLB graph can be found in the `inputs`
field for every step.
@z

@x
```json
    "buildDefinition": {
      "internalParameters": {
        "buildConfig": {
          "llbDefinition": [
            {
              "id": "step0",
              "op": {
                "Op": {
                  "exec": {
                    "meta": {
                      "args": [
                        "/bin/sh",
                        "-c",
                        "go build ."
                      ],
                      "env": [
                        "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "GOPATH=/go",
                        "GOFLAGS=-mod=vendor",
                      ],
                      "cwd": "/src",
                    },
                    "mounts": [...]
                  }
                },
                "platform": {...},
              },
              "inputs": [
                "step8:0",
                "step2:0",
              ]
            },
            ...
          ]
        },
      }
    }
```
@y
```json
    "buildDefinition": {
      "internalParameters": {
        "buildConfig": {
          "llbDefinition": [
            {
              "id": "step0",
              "op": {
                "Op": {
                  "exec": {
                    "meta": {
                      "args": [
                        "/bin/sh",
                        "-c",
                        "go build ."
                      ],
                      "env": [
                        "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "GOPATH=/go",
                        "GOFLAGS=-mod=vendor",
                      ],
                      "cwd": "/src",
                    },
                    "mounts": [...]
                  }
                },
                "platform": {...},
              },
              "inputs": [
                "step8:0",
                "step2:0",
              ]
            },
            ...
          ]
        },
      }
    }
```
@z

@x
### `buildDefinition.internalParameters.builderPlatform`
@y
### `buildDefinition.internalParameters.builderPlatform`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#internalParameters
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#internalParameters
* Included with `mode=min` and `mode=max`.
@z

@x
```json
    "buildDefinition": {
      "internalParameters": {
        "builderPlatform": "linux/amd64"
        ...
      },
    }
```
@y
```json
    "buildDefinition": {
      "internalParameters": {
        "builderPlatform": "linux/amd64"
        ...
      },
    }
```
@z

@x
BuildKit sets the `builderPlatform` of the build machine. Note that this is not
necessarily the platform of the build result that can be determined from the
`in-toto` subject field.
@y
BuildKit sets the `builderPlatform` of the build machine. Note that this is not
necessarily the platform of the build result that can be determined from the
`in-toto` subject field.
@z

@x
### `buildDefinition.resolvedDependencies`
@y
### `buildDefinition.resolvedDependencies`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#resolvedDependencies
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#resolvedDependencies
* Included with `mode=min` and `mode=max`.
@z

@x
Defines all the external artifacts that were part of the build. The value
depends on the type of artifact:
@y
Defines all the external artifacts that were part of the build. The value
depends on the type of artifact:
@z

@x
- The URL of Git repositories containing source code for the image
- HTTP URLs if you are building from a remote tarball, or that was included
  using an `ADD` command in Dockerfile
- Any Docker images used during the build
@y
- The URL of Git repositories containing source code for the image
- HTTP URLs if you are building from a remote tarball, or that was included
  using an `ADD` command in Dockerfile
- Any Docker images used during the build
@z

@x
The URLs to the Docker images will be in
[Package URL](https://github.com/package-url/purl-spec) format.
@y
The URLs to the Docker images will be in
[Package URL](https://github.com/package-url/purl-spec) format.
@z

@x
All the build materials will include the immutable checksum of the artifact.
When building from a mutable tag, you can use the digest information to
determine if the artifact has been updated compared to when the build ran.
@y
All the build materials will include the immutable checksum of the artifact.
When building from a mutable tag, you can use the digest information to
determine if the artifact has been updated compared to when the build ran.
@z

@x
```json
    "buildDefinition": {
      "resolvedDependencies": [
        {
          "uri": "pkg:docker/alpine@3.17?platform=linux%2Famd64",
          "digest": {
            "sha256": "8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4"
          }
        },
        {
          "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
          "digest": {
            "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
          }
        },
        ...
      ],
      ...
    }
```
@y
```json
    "buildDefinition": {
      "resolvedDependencies": [
        {
          "uri": "pkg:docker/alpine@3.17?platform=linux%2Famd64",
          "digest": {
            "sha256": "8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4"
          }
        },
        {
          "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
          "digest": {
            "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
          }
        },
        ...
      ],
      ...
    }
```
@z

@x
### `runDetails.builder.id`
@y
### `runDetails.builder.id`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#builder.id
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#builder.id
* Included with `mode=min` and `mode=max`.
@z

@x
The field is set to the URL of the build, if available.
@y
The field is set to the URL of the build, if available.
@z

@x
```json
    "runDetails": {
      "builder": {
        "id": "https://github.com/docker/buildx/actions/runs/3709599520"
        ...
      },
      ...
    }
```
@y
```json
    "runDetails": {
      "builder": {
        "id": "https://github.com/docker/buildx/actions/runs/3709599520"
        ...
      },
      ...
    }
```
@z

@x
> [!NOTE]
> This value can be set using the `builder-id` attestation parameter.
@y
> [!NOTE]
> This value can be set using the `builder-id` attestation parameter.
@z

@x
### `runDetails.metadata.invocationID`
@y
### `runDetails.metadata.invocationID`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#invocationId
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#invocationId
* Included with `mode=min` and `mode=max`.
@z

@x
Unique identifier for the build invocation. When building a multi-platform image
with a single build request, this value will be the shared by all the platform
versions of the image.
@y
Unique identifier for the build invocation. When building a multi-platform image
with a single build request, this value will be the shared by all the platform
versions of the image.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "invocationID": "rpv7a389uzil5lqmrgwhijwjz",
        ...
      },
      ...
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "invocationID": "rpv7a389uzil5lqmrgwhijwjz",
        ...
      },
      ...
    }
```
@z

@x
### `runDetails.metadata.startedOn`
@y
### `runDetails.metadata.startedOn`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#startedOn
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#startedOn
* Included with `mode=min` and `mode=max`.
@z

@x
Timestamp when the build started.
@y
Timestamp when the build started.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "startedOn": "2021-11-17T15:00:00Z",
        ...
      },
      ...
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "startedOn": "2021-11-17T15:00:00Z",
        ...
      },
      ...
    }
```
@z

@x
### `runDetails.metadata.finishedOn`
@y
### `runDetails.metadata.finishedOn`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#finishedOn
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#finishedOn
* Included with `mode=min` and `mode=max`.
@z

@x
Timestamp when the build finished.
@y
Timestamp when the build finished.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "finishedOn": "2021-11-17T15:01:00Z",
        ...
      },
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "finishedOn": "2021-11-17T15:01:00Z",
        ...
      },
    }
```
@z

@x
### `runDetails.metadata.buildkit_metadata`
@y
### `runDetails.metadata.buildkit_metadata`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Partially included with `mode=min`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Partially included with `mode=min`.
@z

@x
This extension field defines BuildKit-specific additional metadata that is not
part of the SLSA provenance spec.
@y
This extension field defines BuildKit-specific additional metadata that is not
part of the SLSA provenance spec.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "buildkit_metadata": {
          "source": {...},
          "layers": {...},
          "vcs": {...},
        },
        ...
      },
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "buildkit_metadata": {
          "source": {...},
          "layers": {...},
          "vcs": {...},
        },
        ...
      },
    }
```
@z

@x
#### `source`
@y
#### `source`
@z

@x
Only included with `mode=max`.
@y
Only included with `mode=max`.
@z

@x
Defines a source mapping of LLB build steps, defined in the
`buildDefinition.internalParameters.buildConfig.llbDefinition` field, to their
original source code (for example, Dockerfile commands). The `source.locations`
field contains the ranges of all the Dockerfile commands ran in an LLB step.
`source.infos` array contains the source code itself. This mapping is present
if the BuildKit frontend provided it when creating the LLB definition.
@y
Defines a source mapping of LLB build steps, defined in the
`buildDefinition.internalParameters.buildConfig.llbDefinition` field, to their
original source code (for example, Dockerfile commands). The `source.locations`
field contains the ranges of all the Dockerfile commands ran in an LLB step.
`source.infos` array contains the source code itself. This mapping is present
if the BuildKit frontend provided it when creating the LLB definition.
@z

@x
#### `layers`
@y
#### `layers`
@z

@x
Only included with `mode=max`.
@y
Only included with `mode=max`.
@z

@x
Defines the layer mapping of LLB build step mounts defined in
`buildDefinition.internalParameters.buildConfig.llbDefinition` to the OCI
descriptors of equivalent layers. This mapping is present if the layer data was
available, usually when attestation is for an image or if the build step pulled
in image data as part of the build.
@y
Defines the layer mapping of LLB build step mounts defined in
`buildDefinition.internalParameters.buildConfig.llbDefinition` to the OCI
descriptors of equivalent layers. This mapping is present if the layer data was
available, usually when attestation is for an image or if the build step pulled
in image data as part of the build.
@z

@x
#### `vcs`
@y
#### `vcs`
@z

@x
Included with `mode=min` and `mode=max`.
@y
Included with `mode=min` and `mode=max`.
@z

@x
Defines optional metadata for the version control system used for the build. If
a build uses a remote context from Git repository, BuildKit extracts the details
of the version control system automatically and displays it in the
`buildDefinition.externalParameters.configSource` field. But if the build uses
a source from a local directory, the VCS information is lost even if the
directory contained a Git repository. In this case, the build client can send
additional `vcs:source` and `vcs:revision` build options and BuildKit will add
them to the provenance attestations as extra metadata. Note that, contrary to
the `buildDefinition.externalParameters.configSource` field, BuildKit doesn't
verify the `vcs` values, and as such they can't be trusted and should only be
used as a metadata hint.
@y
Defines optional metadata for the version control system used for the build. If
a build uses a remote context from Git repository, BuildKit extracts the details
of the version control system automatically and displays it in the
`buildDefinition.externalParameters.configSource` field. But if the build uses
a source from a local directory, the VCS information is lost even if the
directory contained a Git repository. In this case, the build client can send
additional `vcs:source` and `vcs:revision` build options and BuildKit will add
them to the provenance attestations as extra metadata. Note that, contrary to
the `buildDefinition.externalParameters.configSource` field, BuildKit doesn't
verify the `vcs` values, and as such they can't be trusted and should only be
used as a metadata hint.
@z

@x
### `runDetails.metadata.buildkit_hermetic`
@y
### `runDetails.metadata.buildkit_hermetic`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@z

@x
This extension field is set to true if the build was hermetic and did not access
the network. In Dockerfiles, a build is hermetic if it does not use `RUN`
commands or disables network with `--network=none` flag.
@y
This extension field is set to true if the build was hermetic and did not access
the network. In Dockerfiles, a build is hermetic if it does not use `RUN`
commands or disables network with `--network=none` flag.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "buildkit_hermetic": true,
        ...
      },
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "buildkit_hermetic": true,
        ...
      },
    }
```
@z

@x
### `runDetails.metadata.buildkit_completeness`
@y
### `runDetails.metadata.buildkit_completeness`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@z

@x
This extension field defines if the provenance information is complete. It is
similar to `metadata.completeness` field in SLSA v0.2.
@y
This extension field defines if the provenance information is complete. It is
similar to `metadata.completeness` field in SLSA v0.2.
@z

@x
`buildkit_completeness.request` is true if all the build arguments are included
in the `buildDefinition.externalParameters.request` field. When building with
`min` mode, the build arguments are not included in the provenance information
and request is not complete. Request is also not complete on direct LLB builds
that did not use a frontend.
@y
`buildkit_completeness.request` is true if all the build arguments are included
in the `buildDefinition.externalParameters.request` field. When building with
`min` mode, the build arguments are not included in the provenance information
and request is not complete. Request is also not complete on direct LLB builds
that did not use a frontend.
@z

@x
`buildkit_completeness.resolvedDependencies` is true if
`buildDefinition.resolvedDependencies` field includes all the dependencies of
the build. When building from un-tracked source in a local directory, the
dependencies are not complete, while when building from a remote Git repository
all dependencies can be tracked by BuildKit and
`buildkit_completeness.resolvedDependencies` is true.
@y
`buildkit_completeness.resolvedDependencies` is true if
`buildDefinition.resolvedDependencies` field includes all the dependencies of
the build. When building from un-tracked source in a local directory, the
dependencies are not complete, while when building from a remote Git repository
all dependencies can be tracked by BuildKit and
`buildkit_completeness.resolvedDependencies` is true.
@z

@x
```json
    "runDetails": {
      "metadata": {
        "buildkit_completeness": {
          "request": true,
          "resolvedDependencies": true
        },
        ...
      },
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "buildkit_completeness": {
          "request": true,
          "resolvedDependencies": true
        },
        ...
      },
    }
```
@z

@x
### `runDetails.metadata.buildkit_reproducible`
@y
### `runDetails.metadata.buildkit_reproducible`
@z

@x
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v1.1/provenance#extension-fields
* Included with `mode=min` and `mode=max`.
@z

@x
This extension field defines if the build result is supposed to be byte-by-byte
reproducible. It is similar to `metadata.reproducible` field in SLSA v0.2. This
value can be set by the user with the `reproducible=true` attestation parameter. 
@y
This extension field defines if the build result is supposed to be byte-by-byte
reproducible. It is similar to `metadata.reproducible` field in SLSA v0.2. This
value can be set by the user with the `reproducible=true` attestation parameter. 
@z

@x
```json
    "runDetails": {
      "metadata": {
        "buildkit_reproducible": false,
        ...
      },
    }
```
@y
```json
    "runDetails": {
      "metadata": {
        "buildkit_reproducible": false,
        ...
      },
    }
```
@z

@x
## SLSA v0.2
@y
## SLSA v0.2
@z

@x
### `builder.id`
@y
### `builder.id`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#builder.id
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#builder.id
* Included with `mode=min` and `mode=max`.
@z

@x
The field is set to the URL of the build, if available.
@y
The field is set to the URL of the build, if available.
@z

@x
```json
    "builder": {
      "id": "https://github.com/docker/buildx/actions/runs/3709599520"
    },
```
@y
```json
    "builder": {
      "id": "https://github.com/docker/buildx/actions/runs/3709599520"
    },
```
@z

@x
> [!NOTE]
> This value can be set using the `builder-id` attestation parameter.
@y
> [!NOTE]
> This value can be set using the `builder-id` attestation parameter.
@z

@x
### `buildType`
@y
### `buildType`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#buildType
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#buildType
* Included with `mode=min` and `mode=max`.
@z

@x
The `buildType` field is set to `https://mobyproject.org/buildkit@v1` and can be
used to determine the structure of the provenance content.
@y
The `buildType` field is set to `https://mobyproject.org/buildkit@v1` and can be
used to determine the structure of the provenance content.
@z

@x
```json
    "buildType": "https://mobyproject.org/buildkit@v1",
```
@y
```json
    "buildType": "https://mobyproject.org/buildkit@v1",
```
@z

@x
### `invocation.configSource`
@y
### `invocation.configSource`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.configSource
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.configSource
* Included with `mode=min` and `mode=max`.
@z

@x
Describes the config that initialized the build.
@y
Describes the config that initialized the build.
@z

@x
```json
    "invocation": {
      "configSource": {
        "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
        "digest": {
          "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
        },
        "entryPoint": "Dockerfile"
      },
      ...
    },
```
@y
```json
    "invocation": {
      "configSource": {
        "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
        "digest": {
          "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
        },
        "entryPoint": "Dockerfile"
      },
      ...
    },
```
@z

@x
For builds initialized from a remote context, like a Git or HTTP URL, this
object defines the context URL and its immutable digest in the `uri` and
`digest` fields. For builds using a local frontend, such as a Dockerfile, the
`entryPoint` field defines the path for the frontend file that initialized the
build (`filename` frontend option).
@y
For builds initialized from a remote context, like a Git or HTTP URL, this
object defines the context URL and its immutable digest in the `uri` and
`digest` fields. For builds using a local frontend, such as a Dockerfile, the
`entryPoint` field defines the path for the frontend file that initialized the
build (`filename` frontend option).
@z

@x
### `invocation.parameters`
@y
### `invocation.parameters`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.parameters
* Partially included with `mode=min`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.parameters
* Partially included with `mode=min`.
@z

@x
Describes build inputs passed to the build.
@y
Describes build inputs passed to the build.
@z

@x
```json
    "invocation": {
      "parameters": {
        "frontend": "gateway.v0",
        "args": {
          "build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR": "1",
          "label:FOO": "bar",
          "source": "docker/dockerfile-upstream:master",
          "target": "release"
        },
        "secrets": [
          {
            "id": "GIT_AUTH_HEADER",
            "optional": true
          },
          ...
        ],
        "ssh": [],
        "locals": []
      },
      ...
    },
```
@y
```json
    "invocation": {
      "parameters": {
        "frontend": "gateway.v0",
        "args": {
          "build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR": "1",
          "label:FOO": "bar",
          "source": "docker/dockerfile-upstream:master",
          "target": "release"
        },
        "secrets": [
          {
            "id": "GIT_AUTH_HEADER",
            "optional": true
          },
          ...
        ],
        "ssh": [],
        "locals": []
      },
      ...
    },
```
@z

@x
The following fields are included with both `mode=min` and `mode=max`:
@y
The following fields are included with both `mode=min` and `mode=max`:
@z

@x
- `locals` lists any local sources used in the build, including the build
  context and frontend file.
- `frontend` defines type of BuildKit frontend used for the build. Currently,
  this can be `dockerfile.v0` or `gateway.v0`.
- `args` defines the build arguments passed to the BuildKit frontend.
@y
- `locals` lists any local sources used in the build, including the build
  context and frontend file.
- `frontend` defines type of BuildKit frontend used for the build. Currently,
  this can be `dockerfile.v0` or `gateway.v0`.
- `args` defines the build arguments passed to the BuildKit frontend.
@z

@x
  The keys inside the `args` object reflect the options as BuildKit receives
  them. For example, `build-arg` and `label` prefixes are used for build
  arguments and labels, and `target` key defines the target stage that was
  built. The `source` key defines the source image for the Gateway frontend, if
  used.
@y
  The keys inside the `args` object reflect the options as BuildKit receives
  them. For example, `build-arg` and `label` prefixes are used for build
  arguments and labels, and `target` key defines the target stage that was
  built. The `source` key defines the source image for the Gateway frontend, if
  used.
@z

@x
The following fields are only included with `mode=max`:
@y
The following fields are only included with `mode=max`:
@z

@x
- `secrets` defines secrets used during the build. Note that actual secret
  values are not included.
- `ssh` defines the ssh forwards used during the build.
@y
- `secrets` defines secrets used during the build. Note that actual secret
  values are not included.
- `ssh` defines the ssh forwards used during the build.
@z

@x
### `invocation.environment`
@y
### `invocation.environment`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.environment
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#invocation.environment
* Included with `mode=min` and `mode=max`.
@z

@x
```json
    "invocation": {
      "environment": {
        "platform": "linux/amd64"
      },
      ...
    },
```
@y
```json
    "invocation": {
      "environment": {
        "platform": "linux/amd64"
      },
      ...
    },
```
@z

@x
The only value BuildKit currently sets is the `platform` of the current build
machine. Note that this is not necessarily the platform of the build result that
can be determined from the `in-toto` subject field.
@y
The only value BuildKit currently sets is the `platform` of the current build
machine. Note that this is not necessarily the platform of the build result that
can be determined from the `in-toto` subject field.
@z

@x
### `materials`
@y
### `materials`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#materials
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#materials
* Included with `mode=min` and `mode=max`.
@z

@x
Defines all the external artifacts that were part of the build. The value
depends on the type of artifact:
@y
Defines all the external artifacts that were part of the build. The value
depends on the type of artifact:
@z

@x
- The URL of Git repositories containing source code for the image
- HTTP URLs if you are building from a remote tarball, or that was included
  using an `ADD` command in Dockerfile
- Any Docker images used during the build
@y
- The URL of Git repositories containing source code for the image
- HTTP URLs if you are building from a remote tarball, or that was included
  using an `ADD` command in Dockerfile
- Any Docker images used during the build
@z

@x
The URLs to the Docker images will be in
[Package URL](https://github.com/package-url/purl-spec) format.
@y
The URLs to the Docker images will be in
[Package URL](https://github.com/package-url/purl-spec) format.
@z

@x
All the build materials will include the immutable checksum of the artifact.
When building from a mutable tag, you can use the digest information to
determine if the artifact has been updated compared to when the build ran.
@y
All the build materials will include the immutable checksum of the artifact.
When building from a mutable tag, you can use the digest information to
determine if the artifact has been updated compared to when the build ran.
@z

@x
```json
    "materials": [
      {
        "uri": "pkg:docker/alpine@3.17?platform=linux%2Famd64",
        "digest": {
          "sha256": "8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4"
        }
      },
      {
        "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
        "digest": {
          "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
        }
      },
      ...
    ],
```
@y
```json
    "materials": [
      {
        "uri": "pkg:docker/alpine@3.17?platform=linux%2Famd64",
        "digest": {
          "sha256": "8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4"
        }
      },
      {
        "uri": "https://github.com/moby/buildkit.git#refs/tags/v0.11.0",
        "digest": {
          "sha1": "4b220de5058abfd01ff619c9d2ff6b09a049bea0"
        }
      },
      ...
    ],
```
@z

@x
### `buildConfig`
@y
### `buildConfig`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#buildConfig
* Only included with `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#buildConfig
* Only included with `mode=max`.
@z

@x
Defines the build steps performed during the build.
@y
Defines the build steps performed during the build.
@z

@x
BuildKit internally uses LLB definition to execute the build steps. The LLB
definition of the build steps is defined in `buildConfig.llbDefinition` field.
@y
BuildKit internally uses LLB definition to execute the build steps. The LLB
definition of the build steps is defined in `buildConfig.llbDefinition` field.
@z

@x
Each LLB step is the JSON definition of the
[LLB ProtoBuf API](https://github.com/moby/buildkit/blob/v0.10.0/solver/pb/ops.proto).
The dependencies for a vertex in the LLB graph can be found in the `inputs`
field for every step.
@y
Each LLB step is the JSON definition of the
[LLB ProtoBuf API](https://github.com/moby/buildkit/blob/v0.10.0/solver/pb/ops.proto).
The dependencies for a vertex in the LLB graph can be found in the `inputs`
field for every step.
@z

@x
```json
  "buildConfig": {
    "llbDefinition": [
      {
        "id": "step0",
        "op": {
          "Op": {
            "exec": {
              "meta": {
                "args": [
                  "/bin/sh",
                  "-c",
                  "go build ."
                ],
                "env": [
                  "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                  "GOPATH=/go",
                  "GOFLAGS=-mod=vendor",
                ],
                "cwd": "/src",
              },
              "mounts": [...]
            }
          },
          "platform": {...},
        },
        "inputs": [
          "step8:0",
          "step2:0",
        ]
      },
      ...
    ]
  },
```
@y
```json
  "buildConfig": {
    "llbDefinition": [
      {
        "id": "step0",
        "op": {
          "Op": {
            "exec": {
              "meta": {
                "args": [
                  "/bin/sh",
                  "-c",
                  "go build ."
                ],
                "env": [
                  "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                  "GOPATH=/go",
                  "GOFLAGS=-mod=vendor",
                ],
                "cwd": "/src",
              },
              "mounts": [...]
            }
          },
          "platform": {...},
        },
        "inputs": [
          "step8:0",
          "step2:0",
        ]
      },
      ...
    ]
  },
```
@z

@x
### `metadata.buildInvocationId`
@y
### `metadata.buildInvocationId`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#buildInvocationId
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#buildInvocationId
* Included with `mode=min` and `mode=max`.
@z

@x
Unique identifier for the build invocation. When building a multi-platform image
with a single build request, this value will be the shared by all the platform
versions of the image.
@y
Unique identifier for the build invocation. When building a multi-platform image
with a single build request, this value will be the shared by all the platform
versions of the image.
@z

@x
```json
    "metadata": {
      "buildInvocationID": "rpv7a389uzil5lqmrgwhijwjz",
      ...
    },
```
@y
```json
    "metadata": {
      "buildInvocationID": "rpv7a389uzil5lqmrgwhijwjz",
      ...
    },
```
@z

@x
### `metadata.buildStartedOn`
@y
### `metadata.buildStartedOn`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#buildStartedOn
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#buildStartedOn
* Included with `mode=min` and `mode=max`.
@z

@x
Timestamp when the build started.
@y
Timestamp when the build started.
@z

@x
```json
    "metadata": {
      "buildStartedOn": "2021-11-17T15:00:00Z",
      ...
    },
```
@y
```json
    "metadata": {
      "buildStartedOn": "2021-11-17T15:00:00Z",
      ...
    },
```
@z

@x
### `metadata.buildFinishedOn`
@y
### `metadata.buildFinishedOn`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#buildFinishedOn
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#buildFinishedOn
* Included with `mode=min` and `mode=max`.
@z

@x
Timestamp when the build finished.
@y
Timestamp when the build finished.
@z

@x
```json
    "metadata": {
      "buildFinishedOn": "2021-11-17T15:01:00Z",
      ...
    },
```
@y
```json
    "metadata": {
      "buildFinishedOn": "2021-11-17T15:01:00Z",
      ...
    },
```
@z

@x
### `metadata.completeness`
@y
### `metadata.completeness`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#metadata.completeness
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#metadata.completeness
* Included with `mode=min` and `mode=max`.
@z

@x
Defines if the provenance information is complete.
@y
Defines if the provenance information is complete.
@z

@x
`completeness.parameters` is true if all the build arguments are included in the
`parameters` field. When building with `min` mode, the build arguments are not
included in the provenance information and parameters are not complete.
Parameters are also not complete on direct LLB builds that did not use a
frontend.
@y
`completeness.parameters` is true if all the build arguments are included in the
`parameters` field. When building with `min` mode, the build arguments are not
included in the provenance information and parameters are not complete.
Parameters are also not complete on direct LLB builds that did not use a
frontend.
@z

@x
`completeness.environment` is always true for BuildKit builds.
@y
`completeness.environment` is always true for BuildKit builds.
@z

@x
`completeness.materials` is true if `materials` field includes all the
dependencies of the build. When building from un-tracked source in a local
directory, the materials are not complete, while when building from a remote Git
repository all materials can be tracked by BuildKit and `completeness.materials`
is true.
@y
`completeness.materials` is true if `materials` field includes all the
dependencies of the build. When building from un-tracked source in a local
directory, the materials are not complete, while when building from a remote Git
repository all materials can be tracked by BuildKit and `completeness.materials`
is true.
@z

@x
```json
    "metadata": {
      "completeness": {
        "parameters": true,
        "environment": true,
        "materials": true
      },
      ...
    },
```
@y
```json
    "metadata": {
      "completeness": {
        "parameters": true,
        "environment": true,
        "materials": true
      },
      ...
    },
```
@z

@x
### `metadata.reproducible`
@y
### `metadata.reproducible`
@z

@x
* Ref: https://slsa.dev/spec/v0.2/provenance#metadata.reproducible
* Included with `mode=min` and `mode=max`.
@y
* Ref: https://slsa.dev/spec/v0.2/provenance#metadata.reproducible
* Included with `mode=min` and `mode=max`.
@z

@x
Defines if the build result is supposed to be byte-by-byte reproducible. This
value can be set by the user with the `reproducible=true` attestation parameter.
@y
Defines if the build result is supposed to be byte-by-byte reproducible. This
value can be set by the user with the `reproducible=true` attestation parameter.
@z

@x
```json
    "metadata": {
      "reproducible": false,
      ...
    },
```
@y
```json
    "metadata": {
      "reproducible": false,
      ...
    },
```
@z

@x
### `metadata.https://mobyproject.org/buildkit@v1#hermetic`
@y
### `metadata.https://mobyproject.org/buildkit@v1#hermetic`
@z

@x
Included with `mode=min` and `mode=max`.
@y
Included with `mode=min` and `mode=max`.
@z

@x
This extension field is set to true if the build was hermetic and did not access
the network. In Dockerfiles, a build is hermetic if it does not use `RUN`
commands or disables network with `--network=none` flag.
@y
This extension field is set to true if the build was hermetic and did not access
the network. In Dockerfiles, a build is hermetic if it does not use `RUN`
commands or disables network with `--network=none` flag.
@z

@x
```json
    "metadata": {
      "https://mobyproject.org/buildkit@v1#hermetic": true,
      ...
    },
```
@y
```json
    "metadata": {
      "https://mobyproject.org/buildkit@v1#hermetic": true,
      ...
    },
```
@z

@x
### `metadata.https://mobyproject.org/buildkit@v1#metadata`
@y
### `metadata.https://mobyproject.org/buildkit@v1#metadata`
@z

@x
Partially included with `mode=min`.
@y
Partially included with `mode=min`.
@z

@x
This extension field defines BuildKit-specific additional metadata that is not
part of the SLSA provenance spec.
@y
This extension field defines BuildKit-specific additional metadata that is not
part of the SLSA provenance spec.
@z

@x
```json
    "metadata": {
      "https://mobyproject.org/buildkit@v1#metadata": {
        "source": {...},
        "layers": {...},
        "vcs": {...},
      },
      ...
    },
```
@y
```json
    "metadata": {
      "https://mobyproject.org/buildkit@v1#metadata": {
        "source": {...},
        "layers": {...},
        "vcs": {...},
      },
      ...
    },
```
@z

@x
#### `source`
@y
#### `source`
@z

@x
Only included with `mode=max`.
@y
Only included with `mode=max`.
@z

@x
Defines a source mapping of LLB build steps, defined in the
`buildConfig.llbDefinition` field, to their original source code (for example,
Dockerfile commands). The `source.locations` field contains the ranges of all
the Dockerfile commands ran in an LLB step. `source.infos` array contains the
source code itself. This mapping is present if the BuildKit frontend provided it
when creating the LLB definition.
@y
Defines a source mapping of LLB build steps, defined in the
`buildConfig.llbDefinition` field, to their original source code (for example,
Dockerfile commands). The `source.locations` field contains the ranges of all
the Dockerfile commands ran in an LLB step. `source.infos` array contains the
source code itself. This mapping is present if the BuildKit frontend provided it
when creating the LLB definition.
@z

@x
#### `layers`
@y
#### `layers`
@z

@x
Only included with `mode=max`.
@y
Only included with `mode=max`.
@z

@x
Defines the layer mapping of LLB build step mounts defined in
`buildConfig.llbDefinition` to the OCI descriptors of equivalent layers. This
mapping is present if the layer data was available, usually when attestation is
for an image or if the build step pulled in image data as part of the build.
@y
Defines the layer mapping of LLB build step mounts defined in
`buildConfig.llbDefinition` to the OCI descriptors of equivalent layers. This
mapping is present if the layer data was available, usually when attestation is
for an image or if the build step pulled in image data as part of the build.
@z

@x
#### `vcs`
@y
#### `vcs`
@z

@x
Included with `mode=min` and `mode=max`.
@y
Included with `mode=min` and `mode=max`.
@z

@x
Defines optional metadata for the version control system used for the build. If
a build uses a remote context from Git repository, BuildKit extracts the details
of the version control system automatically and displays it in the
`invocation.configSource` field. But if the build uses a source from a local
directory, the VCS information is lost even if the directory contained a Git
repository. In this case, the build client can send additional `vcs:source` and
`vcs:revision` build options and BuildKit will add them to the provenance
attestations as extra metadata. Note that, contrary to the
`invocation.configSource` field, BuildKit doesn't verify the `vcs` values, and
as such they can't be trusted and should only be used as a metadata hint.
@y
Defines optional metadata for the version control system used for the build. If
a build uses a remote context from Git repository, BuildKit extracts the details
of the version control system automatically and displays it in the
`invocation.configSource` field. But if the build uses a source from a local
directory, the VCS information is lost even if the directory contained a Git
repository. In this case, the build client can send additional `vcs:source` and
`vcs:revision` build options and BuildKit will add them to the provenance
attestations as extra metadata. Note that, contrary to the
`invocation.configSource` field, BuildKit doesn't verify the `vcs` values, and
as such they can't be trusted and should only be used as a metadata hint.
@z
